### ISSUE TITLE
TensorFlow 2?

### ISSUE THREAD

**Issue by teamclouday** [Trusted-AI/AIF360#203]
Will there be a plan to upgrade code for Adversarial Debiasing to fit TensorFlow 2 API?  
Or at least call the `tf`-related functions in `tf.compat.v1`?

**Comment by alexlaurence** [comment]
So far no news on this... I have been waiting for a while now.

**Comment by hoffmansc** [comment]
If either of you would like to give it a shot, swapping the imports with `import tensorflow.compat.v1 as tf` will probably work for now if you're willing to test it.

**Comment by briannakathrynm** [comment]
Some of the functions, such as .fit(), won't work wit the compat version of TF. Is there any resolution for this?

**Comment by bertainsikt** [comment]
Hi, I can't run aif360 because of the incompatibility with tensorflow 2, is there any solution for that?
