### ISSUE TITLE
aif360.metrics.DatasetMetric metric_fun options

### ISSUE THREAD

**Issue by mjorgen1** [Trusted-AI/AIF360#221]
I am interested in using the "difference" and "ratio" methods from the [DatasetMetric](https://aif360.readthedocs.io/en/latest/modules/generated/aif360.metrics.DatasetMetric.html) class. I need to include "metric_fun" as a parameter for both of those methods; however, I cannot find a list of possible metric_fun options. I looked in the class' [code](https://github.com/Trusted-AI/AIF360/blob/master/aif360/metrics/dataset_metric.py#L73-L77) as well but still couldn't find a description of the parameter nor options for it. Where can I find this? Thanks so much!

**Comment by hoffmansc** [comment]
You can use any of the functions of the form: `metric_fun(privileged)`, e.g., [`disparate_impact()`](https://github.com/Trusted-AI/AIF360/blob/master/aif360/metrics/binary_label_dataset_metric.py#L114) is just `self.ratio(self.base_rate)`. Many of these combinations already exist and are usually named like `[metric_fun]_difference()` and `[metric_fun]_ratio()` but you can also come up with novel ones if they make sense.

**Comment by mjorgen1** [comment]
Hi @hoffmansc I got it now. Thanks for the clarification!
