### ISSUE TITLE
fetch_adult() and fetch_german() does not work in sklearn package

### ISSUE THREAD

**Issue by bendiste** [Trusted-AI/AIF360#231]
I have been trying to use the sklearn extension of AIF360 and import some datasets. For that, I have followed one of the example Jupyter notebooks called [demo_exponentiated_gradient_reduction_sklearn.ipynb](https://github.com/Trusted-AI/AIF360/blob/master/examples/sklearn/demo_exponentiated_gradient_reduction_sklearn.ipynb). I have tried the following code which is literally the first two blocks of that Jupyter notebook:

`%matplotlib inline`
`import matplotlib.pyplot as plt`
`import numpy as np`
`import pandas as pd`

`from sklearn.linear_model import LogisticRegression`
`from sklearn.metrics import accuracy_score`
`from sklearn.model_selection import GridSearchCV, train_test_split`
`from sklearn.preprocessing import OneHotEncoder`
 
`from aif360.sklearn.inprocessing import ExponentiatedGradientReduction`

`from aif360.sklearn.datasets import fetch_adult, fetch_german`
`from aif360.sklearn.metrics import disparate_impact_ratio, average_odds_error, generalized_fpr`
`from aif360.sklearn.metrics import generalized_fnr, difference`

`X, y, sample_weight = fetch_adult()`

And I get the following error:

`AttributeError: 'NoneType' object has no attribute 'items'`

I could not find the reason for this error. Can anyone help with it?

**Comment by pronics2004** [comment]
This appears to be specific to scikit-learn==0.24. Using scikit-learn<0.24 might resolve this.

CC: @nrkarthikeyan @hoffmansc

**Comment by hoffmansc** [comment]
I couldn't replicate with AIF360 v0.4.0. Does that fix it?

**Comment by bendiste** [comment]
Yes, it does work well now.
