### ISSUE TITLE
How I can use AIF360 in Computer Vision

### ISSUE THREAD

**Issue by ticlazau** [Trusted-AI/AIF360#233]
Hello,

I am looking to use AIF360 with an image dataset for object detection.
Has anyone succeeded to use it in this case? or even more simple cases such as image classification?

Thanks,
F.M.

**Comment by nrkarthikeyan** [comment]
If you have tabular meta data along with the image datasets, you can use AIF360 with the tabular meta data. Directly using image data is not possible.
