### ISSUE TITLE
Can AIF360 detect and mitigate bias on a dataset without the protected attributes?

### ISSUE THREAD

**Issue by adidutt** [Trusted-AI/AIF360#235]
If my dataset does not have protected attributes, can AIF360 detect and mitigate bias in this case? I am trying to detect and mitigate bias using pre processing algorithms before training the model.

**Comment by nrkarthikeyan** [comment]
You need protected attributes for estimating the amount of unwanted bias with respect to outcomes. So this is not possible.

**Comment by adidutt** [comment]
Thank You!
