### ISSUE TITLE
Bias in multi-class protected attribute

### ISSUE THREAD

**Issue by vatsalnayak895** [Trusted-AI/AIF360#236]
I am working on understanding Bias in a multi-class protected attribute, where one particular class is a privileged class (Dataset Contains more favorable outcomes for this class, as compared to other subclasses) and another particular class is an unprivileged class (Dataset contains the least favorable outcome for this class, as compared to other subclasses). How do I handle other subclasses of this protected attribute?
 For example, if I have 4 subclasses in my protected attribute "Region" in a binary label prediction problem, where "North" is privileged and "West" is unprivileged, how should I handle the other 2 subclasses ("South" & "East")?

**Comment by krvarshney** [comment]
You have a few options. You can simply drop the records associated with South and East, and only compute the group fairness metrics between North and West. Or if you have reason to believe that for some subject matter reason that South and/or East are privileged or unprivileged, you can put them together with North and/or West.
