### ISSUE TITLE
Privileged class in BankDataset

### ISSUE THREAD

**Issue by chenzhenpeng18** [Trusted-AI/AIF360#265]
In AIF360, age>=25 is set as the privileged class in BankDataset. However, I find that this class is not really privileged.

In fact, 12.35% of samples with age>=25 were marked as "yes", while 23.03% of samples with age<25 were marked as "yes". Therefore, I think age<25 should be the privileged class.

**Comment by hoffmansc** [comment]
According to this, https://wires.onlinelibrary.wiley.com/doi/pdf/10.1002/widm.1452 (Section 3.1.5), we should be using: age<25,age>60 vs 25<=age<=60
