### ISSUE TITLE
List of 70 Metrics

### ISSUE THREAD

**Issue by OGK0** [Trusted-AI/AIF360#275]
Hello,

This is a simple question - Can someone point me to the master list of 70+ fairness metrics ? I read on the AI 360 site that "There are more than 70 metrics in the GitHub repository already. Add new metrics to the repository and use the Slack channel to let the community know about them." (https://aif360.mybluemix.net/).

Apologies if I missed the link. Thanks in advance.

**Comment by nrkarthikeyan** [comment]
Closing in lieu of @krvarshney 's response
