### ISSUE TITLE
Module "aif360.metrics.mdss_classification_metric" not found

### ISSUE THREAD

**Issue by mrtobie** [Trusted-AI/AIF360#293]
Hi all,
i run into an error when trying to execute the example "demo_mdss_classifier_metric.ipynb".
I already tried on windows and linux. Here is my code and the occuring error:

```python
!pip install aif360
```

    Requirement already satisfied: aif360 in ./anaconda3/envs/master/lib/python3.7/site-packages (0.4.0)
    Requirement already satisfied: tempeh in ./anaconda3/envs/master/lib/python3.7/site-packages (from aif360) (0.1.12)
    Requirement already satisfied: pandas>=0.24.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from aif360) (1.3.5)
    Requirement already satisfied: scikit-learn>=0.22.1 in ./anaconda3/envs/master/lib/python3.7/site-packages (from aif360) (1.0.2)
    Requirement already satisfied: matplotlib in ./anaconda3/envs/master/lib/python3.7/site-packages (from aif360) (3.5.1)
    Requirement already satisfied: scipy<1.6.0,>=1.2.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from aif360) (1.5.4)
    Requirement already satisfied: numpy>=1.16 in ./anaconda3/envs/master/lib/python3.7/site-packages (from aif360) (1.21.5)
    Requirement already satisfied: python-dateutil>=2.7.3 in ./anaconda3/envs/master/lib/python3.7/site-packages (from pandas>=0.24.0->aif360) (2.8.2)
    Requirement already satisfied: pytz>=2017.3 in ./anaconda3/envs/master/lib/python3.7/site-packages (from pandas>=0.24.0->aif360) (2021.3)
    Requirement already satisfied: six>=1.5 in ./anaconda3/envs/master/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->aif360) (1.16.0)
    Requirement already satisfied: threadpoolctl>=2.0.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from scikit-learn>=0.22.1->aif360) (3.1.0)
    Requirement already satisfied: joblib>=0.11 in ./anaconda3/envs/master/lib/python3.7/site-packages (from scikit-learn>=0.22.1->aif360) (1.1.0)
    Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/envs/master/lib/python3.7/site-packages (from matplotlib->aif360) (1.3.2)
    Requirement already satisfied: pillow>=6.2.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from matplotlib->aif360) (9.0.1)
    Requirement already satisfied: fonttools>=4.22.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from matplotlib->aif360) (4.29.1)
    Requirement already satisfied: cycler>=0.10 in ./anaconda3/envs/master/lib/python3.7/site-packages (from matplotlib->aif360) (0.11.0)
    Requirement already satisfied: pyparsing>=2.2.1 in ./anaconda3/envs/master/lib/python3.7/site-packages (from matplotlib->aif360) (3.0.7)
    Requirement already satisfied: packaging>=20.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from matplotlib->aif360) (21.3)
    Requirement already satisfied: requests in ./anaconda3/envs/master/lib/python3.7/site-packages (from tempeh->aif360) (2.27.1)
    Requirement already satisfied: shap in ./anaconda3/envs/master/lib/python3.7/site-packages (from tempeh->aif360) (0.40.0)
    Requirement already satisfied: memory-profiler in ./anaconda3/envs/master/lib/python3.7/site-packages (from tempeh->aif360) (0.60.0)
    Requirement already satisfied: pytest in ./anaconda3/envs/master/lib/python3.7/site-packages (from tempeh->aif360) (7.0.1)
    Requirement already satisfied: psutil in ./anaconda3/envs/master/lib/python3.7/site-packages (from memory-profiler->tempeh->aif360) (5.9.0)
    Requirement already satisfied: importlib-metadata>=0.12 in ./anaconda3/envs/master/lib/python3.7/site-packages (from pytest->tempeh->aif360) (4.11.2)
    Requirement already satisfied: iniconfig in ./anaconda3/envs/master/lib/python3.7/site-packages (from pytest->tempeh->aif360) (1.1.1)
    Requirement already satisfied: attrs>=19.2.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from pytest->tempeh->aif360) (21.4.0)
    Requirement already satisfied: tomli>=1.0.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from pytest->tempeh->aif360) (2.0.1)
    Requirement already satisfied: pluggy<2.0,>=0.12 in ./anaconda3/envs/master/lib/python3.7/site-packages (from pytest->tempeh->aif360) (1.0.0)
    Requirement already satisfied: py>=1.8.2 in ./anaconda3/envs/master/lib/python3.7/site-packages (from pytest->tempeh->aif360) (1.11.0)
    Requirement already satisfied: typing-extensions>=3.6.4 in ./anaconda3/envs/master/lib/python3.7/site-packages (from importlib-metadata>=0.12->pytest->tempeh->aif360) (4.1.1)
    Requirement already satisfied: zipp>=0.5 in ./anaconda3/envs/master/lib/python3.7/site-packages (from importlib-metadata>=0.12->pytest->tempeh->aif360) (3.7.0)
    Requirement already satisfied: charset-normalizer~=2.0.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from requests->tempeh->aif360) (2.0.12)
    Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./anaconda3/envs/master/lib/python3.7/site-packages (from requests->tempeh->aif360) (1.26.8)
    Requirement already satisfied: idna<4,>=2.5 in ./anaconda3/envs/master/lib/python3.7/site-packages (from requests->tempeh->aif360) (3.3)
    Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/master/lib/python3.7/site-packages (from requests->tempeh->aif360) (2021.10.8)
    Requirement already satisfied: numba in ./anaconda3/envs/master/lib/python3.7/site-packages (from shap->tempeh->aif360) (0.55.1)
    Requirement already satisfied: cloudpickle in ./anaconda3/envs/master/lib/python3.7/site-packages (from shap->tempeh->aif360) (2.0.0)
    Requirement already satisfied: tqdm>4.25.0 in ./anaconda3/envs/master/lib/python3.7/site-packages (from shap->tempeh->aif360) (4.63.0)
    Requirement already satisfied: slicer==0.0.7 in ./anaconda3/envs/master/lib/python3.7/site-packages (from shap->tempeh->aif360) (0.0.7)
    Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in ./anaconda3/envs/master/lib/python3.7/site-packages (from numba->shap->tempeh->aif360) (0.38.0)
    Requirement already satisfied: setuptools in ./anaconda3/envs/master/lib/python3.7/site-packages (from numba->shap->tempeh->aif360) (58.0.4)

```python
import sys
import itertools
sys.path.append("../")

from aif360.metrics import BinaryLabelDatasetMetric 
from aif360.metrics.mdss_classification_metric import MDSSClassificationMetric
from aif360.metrics.mdss.ScoringFunctions.Bernoulli import Bernoulli


from aif360.algorithms.preprocessing.optim_preproc_helpers.data_preproc_functions import load_preproc_data_compas
from aif360.algorithms.inprocessing.meta_fair_classifier import MetaFairClassifier

from IPython.display import Markdown, display
import numpy as np
import pandas as pd

from aif360.metrics import BinaryLabelDatasetMetric 
```

    ---------------------------------------------------------------------------

    ModuleNotFoundError                       Traceback (most recent call last)

    <ipython-input-19-91715e3e1308> in <module>
          4 
          5 from aif360.metrics import BinaryLabelDatasetMetric
    ----> 6 from aif360.metrics.mdss_classification_metric import MDSSClassificationMetric
          7 from aif360.metrics.mdss.ScoringFunctions.Bernoulli import Bernoulli
          8 

    ModuleNotFoundError: No module named 'aif360.metrics.mdss_classification_metric'

**Comment by Adebayo-Oshingbesan** [comment]
Hi.

Try installing the latest code version from the repo directly using pip install git+https://github.com/Trusted-AI/AIF360.git. The pip version is about a year old.

**Comment by mrtobie** [comment]
Thanks, seems to work now!
