### ISSUE TITLE
 How can double protected attributes pass into some inprocessing algoritms such as MetaFairClassifier, PrejudiceRemover?

### ISSUE THREAD

**Issue by zhanggy358** [Trusted-AI/AIF360#296]
Why some inprocessing algoritms such as MetaFairClassifier, PrejudiceRemover and so on, can only support one protected attributes input, but don not support double or many protected attributes?

1.MetaFairClassifier(tau=0.7, sensitive_attr='sex', type="fdr"): sensitive_attr is a str parameter not list
2.PrejudiceRemover(sensitive_attr='age', eta=25.0): also sensitive_attr is a str parameter  not list

**Comment by nrkarthikeyan** [comment]
You can create a synthetic protected attribute that combines multiple protected attributes and use them (in case the algorithm supports multiple values for a single protected attribute).

**Comment by anilsh** [comment]
I am trying to use multiple protected attributes. Do we have an example how to create a synthetic attribute for this?
