### ISSUE TITLE
AIF360 installation

### ISSUE THREAD

**Issue by myarris** [Trusted-AI/AIF360#298]
I  keep getting this error when running load_aif360_lib():
  cannot change value of locked binding for 'datasets'

Do you know why this is a problem?

**Comment by SSaishruthi** [comment]
Thanks for posting the issue. @myarris 

Can you please add all the steps you followed for package installation?

Notes that I have to help with installation:

```
install.packages("reticulate")
Check conda - reticulate::conda_list()
reticulate::conda_create(envname = "r-test")
reticulate::use_miniconda(condaenv = "r-test", required = TRUE)
Check config - reticulate::py_config()
devtools::install_github("Trusted-AI/AIF360/aif360/aif360-r")
aif360::install_aif360(envname = "r-test")

Make sure you are in correct env - reticulate::use_miniconda(condaenv = "r-test", required = TRUE)

library(aif360)
load_aif360_lib()
```

**Comment by myarris** [comment]
This is the code I  have used for package installation:

install.packages("reticulate")
reticulate::conda_list()
reticulate::conda_create(envname = "r-test")
reticulate::use_miniconda(condaenv = "r-test", required = TRUE)
reticulate::py_config()
devtools::install_github("Trusted-AI/AIF360/aif360/aif360-r")
aif360::install_aif360(envname = "r-test")

reticulate::use_miniconda(condaenv = "r-test", required = TRUE)

library(aif360)
load_aif360_lib()

help(aif360)

df <- adult_dataset()

**Comment by SSaishruthi** [comment]
@myarris Is this issue resolved? Were you able to install the package?

**Comment by monicabvroman** [comment]
Dear @SSaishruthi , I am having the same issue. When I run load_aif360)lib(), my R session crashes. I added the lines of code you suggested and now it crashes when I run this line:

reticulate::use_miniconda(condaenv = "r-test", required = TRUE)

Your help is appreciated!

**Comment by milevavantuyl** [comment]
@myarris and @monicabvroman Thanks for informing us of these issues. The locked binding and load_aif360_lib() issues have been addressed via code fixes and updates to the troubleshooting section of the README. Closing this issue now.
