### ISSUE TITLE
BUG: Problem when Unpack -- the String in line 147 should be merge to the line 146.

### ISSUE THREAD

**Issue by alfayohannis** [Trusted-AI/AIF360#304]
https://github.com/Trusted-AI/AIF360/blob/73263a36a89d875006f57aa1a2358c58e7f1e3ea/aif360/explainers/metric_json_explainer.py#L146-L147

BUG: Problem when Unpack -- the String in line 147 should be merge to the line 146.

**Comment by nrkarthikeyan** [comment]
duplicate of #227
