### ISSUE TITLE
Download LawSchool dataset directly from SEAPHE

### ISSUE THREAD

**Issue by hoffmansc** [Trusted-AI/AIF360#359]
http://www.seaphe.org/databases.php

This way we can remove the dependency on tempeh. We can essentially copy this file (preserving the copyright notice): https://github.com/microsoft/tempeh/blob/main/tempeh/datasets/seaphe_datasets.py

See also [meps_datasets.py](https://github.com/Trusted-AI/AIF360/blob/master/aif360/sklearn/datasets/meps_datasets.py) for another example of downloading/unzipping.

Relevant files:
[tempeh_datasets.py](https://github.com/Trusted-AI/AIF360/blob/master/aif360/sklearn/datasets/tempeh_datasets.py)
[law_school_gpa_dataset.py](https://github.com/Trusted-AI/AIF360/blob/master/aif360/datasets/law_school_gpa_dataset.py)

See [demo_grid_search_reduction_regression_sklearn.ipynb](https://github.com/Trusted-AI/AIF360/blob/master/examples/sklearn/demo_grid_search_reduction_regression_sklearn.ipynb) for example usage.

Behavior should be essentially the same as tempeh except dropping of NAs can be handled later so these should be kept.

**Comment by anupamamurthi** [comment]
Possible Tasks:

- [ ]  Ensure the license permits open source us
- [ ]  Verify that this dataset is appropriate for fairness tasks and subset it accordingly (removing un-necessary columns etc.)
- [ ]  Ensure we have instance level records with protected attributes and outcomes
- [ ]  First create sklearn-compatible dataset (dataframe) and an appropriate "classic" dataset (second priority)
- [ ]  Create a simple notebook where the dataset is consumed and simple fairness measures and computed at least.

**Comment by EktaBhaskar** [comment]
please assign me this issue.

**Comment by vandanapathare** [comment]
Can I get this issue  assigned
