### ISSUE TITLE
Is there any guide to use postProcessing technique on text dataset?

### ISSUE THREAD

**Issue by bloodteller123** [Trusted-AI/AIF360#418]
I'm doing some text classifications, and the dataset has only 'text' and 'label' attributes. I was wondering how to apply postProcessing techniques on my predictions as it seems that the library doesn't accept text input..
Thank you

**Comment by nrkarthikeyan** [comment]
You can create a dataset with only protected attributes, labels, and scores. That is sufficient for post-processing techniques generally.

**Comment by bloodteller123** [comment]
Thank you for the reply! I wonder what the scores are in the context of text classification? (I was using Bert for classification task)

**Comment by nrkarthikeyan** [comment]
Predicted probabilities for classification of the positive class.
