### ISSUE TITLE
404 Not Found: Requested route ('aif360.mybluemix.net') does not exist.

### ISSUE THREAD

**Issue by live2awesome** [Trusted-AI/AIF360#459]
![image](https://github.com/Trusted-AI/AIF360/assets/67458633/afe13eba-eb60-4abe-a635-dcc1bcc16570)

**Comment by michaelhind** [comment]
Thanks for reporting this Parimal.  We are working on this issue and hope to have it resolved soon.

**Comment by carywoods** [comment]
thank you any update on this

**Comment by mnagired** [comment]
The website is back up here: https://aif360.res.ibm.com/
