### ISSUE TITLE
`if_delegate_has_method` is deprecated, use `available_if` instead

### ISSUE THREAD

**Issue by hoffmansc** [Trusted-AI/AIF360#475]
`if_delegate_has_method` is used in some places in the `aif360.sklearn` code (e.g., [reweighing.py](https://github.com/Trusted-AI/AIF360/blob/master/aif360/sklearn/preprocessing/reweighing.py)) but this is deprecated now in favor of [`available_if`](https://scikit-learn.org/stable/modules/generated/sklearn.utils.metaestimators.available_if.html)

e.g.,
https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/ensemble/_stacking.py#L660

**Comment by AmirAflak** [comment]
would like to take it :)

**Comment by divyaamin9825** [comment]
Hi I'd like to take this issue as well
