### ISSUE TITLE
Building docs with python >= 3.10 and sphinx < 2 fails

### ISSUE THREAD

**Issue by phantom-duck** [Trusted-AI/AIF360#496]
Building the docs currently fails, because python versions >=3.10 and the requirement `sphinx<2` in `setup.py` are incompatible. In those old versions of sphinx, and specifically in `sphinx/ext/napoleon/docstring.py`, the component `collections.Callable` is used. However, this has been moved to `collections.abc` since python 3.3, and removed altogether from `collections` since python 3.10 (sources: [stackoverflow](https://stackoverflow.com/questions/69515086/error-attributeerror-collections-has-no-attribute-callable-using-beautifu), [python docs 1](https://docs.python.org/3/whatsnew/3.10.html#removed), [github issue](https://github.com/python/cpython/issues/81505), [python docs 2](https://docs.python.org/3.9/library/collections.html))

Steps to reproduce:

```bash
git clone https://github.com/Trusted-AI/AIF360.git
conda create -n aif360 python>=3.10
conda activate aif360
cd AIF360
pip install -e '.[all]'
cd docs
make html
```

The last command fails with error:
```console
Exception occurred:
  File "path\to\sphinx\ext\napoleon\docstring.py", line 123, in __init__
    elif isinstance(obj, collections.Callable):  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
```

I am not sure whether this is an appropriate issue for here or it would be better suited in sphinx, since sphinx itself does not specify an upper bound on the python version. Please let me know.

**Comment by PaarthShah** [comment]
I thought I was having the same problem (even cited this issue). However, it turned out to be completely resolved by installing the newest `sphinx` version: currently this repo is pinned to a much older one: https://github.com/Trusted-AI/AIF360/blob/2653b7b3ce5b8ae62ac9abfc16b1741ea601b435/requirements.txt#L28

**Comment by phantom-duck** [comment]
Thank you, I should have made it more clear that the problem is not sphinx per se, but only that its version is very old. I have changed the title of the current issue to more clearly reflect this.

My suggestion would also be to update the version of `sphinx` to a newer one; keeping in mind, though, that I do not know why the version was pinned as such to begin with.
