### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by baraldian** [Trusted-AI/AIF360#497]
https://github.com/Trusted-AI/AIF360/blob/2653b7b3ce5b8ae62ac9abfc16b1741ea601b435/aif360/algorithms/preprocessing/optim_preproc_helpers/data_preproc_functions.py#L268C47-L268C65

aif360/algorithms/preprocessing/optim_preproc_helpers/data_preproc_functions.py' , line 268, in <lambda>
    df['age'] = df['age'].apply(lambda x: np.float(x >= 26))

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by hoffmansc** [comment]
would you be willing to put together a PR fixing this? I think we can just replace it with `float`, no problem.

**Comment by baraldian** [comment]
> would you be willing to put together a PR fixing this? I think we can just replace it with `float`, no problem.

Done!
Thank you for your suggestion.
Did I do it properly?
